name: Laravel CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: neondb
          POSTGRES_USER: neondb_owner
          POSTGRES_PASSWORD: endpoint=ep-summer-thunder-a4eytc3i$8CfHmgUpw0GR
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
    - name: Print Current Directory
      run: pwd
    - name: List Current Directory
      run: ls -la
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
      php-version: '8.2'
    # Check if PHP is already installed
    - name: Check PHP Version
      run: php -v

    # Check if Composer is already installed
    - name: Check Composer Version
      run: composer -v

    - name: Set up .env with PostgreSQL (Neon)
      run: |
        cp .env.example .env
        echo "DB_CONNECTION=pgsql" >> .env
        echo "DB_HOST=ep-summer-thunder-a4eytc3i.us-east-1.aws.neon.tech" >> .env
        echo "DB_PORT=5432" >> .env
        echo "DB_DATABASE=neondb" >> .env
        echo "DB_USERNAME=neondb_owner" >> .env
        echo "DB_PASSWORD=endpoint=ep-summer-thunder-a4eytc3i\$8CfHmgUpw0GR" >> .env
        echo "DB_SSLMODE=require" >> .env
        
    - name: Install Composer Dependencies
      run: composer update
      working-directory: /home/runner/work/LaravelWebreathProject/LaravelWebreathProject
        
    - name: Install Composer Dependencies
      run: composer install
      working-directory: /home/runner/work/LaravelWebreathProject/LaravelWebreathProject
    - name: Run Migrations
      run: php artisan migrate --force
      working-directory: /home/runner/work/LaravelWebreathProject/LaravelWebreathProject
    - name: Start Laravel Development Server
      run: php artisan serve
      working-directory: /home/runner/work/LaravelWebreathProject/LaravelWebreathProject
    
      
    
    - name: Deploy to AWS
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
